name: Build docs

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    name: Sphinx docs to gh-pages
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.12"
          cache: true
      - name: Install dependencies
        run: pdm sync
      - name: Build docs
        run: pdm docs
      - name: Create .nojekyll in case 'sphinx.ext.githubpages' is not used
        run: touch "docs/_build/.nojekyll"
      - name: Set the committer name and email
        run: |
          author_name="$(git show --format=%an -s)"
          author_email="$(git show --format=%ae -s)"
          git config user.name "$author_name"
          git config user.email "$author_email"
      - name: Create gh-pages branch if needed
        run: |
          if [[ -z "$(git ls-remote --heads origin gh-pages)" ]]; then
             echo "Creating gh-pages branch"
             git checkout --orphan gh-pages
             git reset --hard
             git commit --allow-empty -m "First commit to create gh-pages branch"
             git push origin gh-pages
             echo "Created gh-pages branch"
             git checkout "$GITHUB_REF"
          else
             echo "Branch gh-pages already exists"
          fi
      - name: Commit to gh-pages branch and push
        run: |
          git add -f "docs/_build/"
          git commit -m "From $GITHUB_REF $GITHUB_SHA"
          git push origin `git subtree split --prefix "docs/_build/" "$GITHUB_REF"`:gh-pages --force
